### ISSUE TITLE
 GPL-3.0 license

### ISSUE THREAD

**Issue by Nineteendo** [j0912345/pvz2_obb_tools#2]
So, you have used my tool and quickbms for documentation.
That's great, but you must use the same license as we did. The [GPL-3.0 license](https://github.com/Nineteendo/PVZ2tools/blob/master/LICENSE)
This license requires you to do that.

Otherwise you must get rid of all of the code you used from us.

**Comment by j0912345** [comment]
oh right. i should have thought of that. thanks for telling me.
